TYPE="type"
ARGS="args"
RETURN="return"
EXCP="exceptions"
TARGET="target"
FUNC="func"
OBJC="objc"



# cleanup for test
def cleanup():
  if "testfile.txt.a" in listfiles():
    removefile("testfile.txt.a")
  if "testfile.txt.b" in listfiles():
    removefile("testfile.txt.b")
	
# assumption 4 - creating 2 files with the same name should be ok
# I will create ABFile, and then again ABFile with the same name
# No exceptions should be thrown

try:
	
	cleanup()
	myfile1=ABopenfile("testfile.txt",True)
	myfile2=ABopenfile("testfile.txt",True)
	
# We dont expect exceptions on creating file because we cleaned up before
# and performing within basic success scenario => exception = test failure
except Exception as e: 
	log("[(4) ERROR]: Unexpected exception while creating 2 files with the same name: " + str(e) + "\n")
	
finally:
	pass