Trying reference_monitor_aab641.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
(2) [ERROR]: AssertionError - After closing ABFile we get wrong content written to it! Here is how it was found: 1. New ABFile was created for writing. 2. Writeat was called with incorrect content (TerriblyWrongContent) 3. File was closed and reopened for reading. 4. Readat was called. Expected: SE, actual: S12345E
Trying reference_monitor_aat414.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_aav304.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_abs662.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5042565 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_ac5769.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_afl294.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_ag6026.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_aj1973.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_ajf500.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5156945 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_al4146.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.4682372 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<class 'exception_hierarchy.FileClosedError'>' which is forbidden. 
---
Trying reference_monitor_ap4066.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_aps549.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.509118 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<class 'exception_hierarchy.RepyArgumentError'>' which is forbidden. 
---
Trying reference_monitor_apt321.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_ar5439.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.4955275 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_as11294.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5024699 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<class 'exception_hierarchy.RepyArgumentError'>' which is forbidden. 
---
Trying reference_monitor_as11419.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5163091 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_as8513.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5182263 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_ash521.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
%s is not valid testfile.txt.bTrying reference_monitor_at3761.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_bd1308.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_bt1124.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_bws272.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_cb3172.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_ckc358.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_cpb325.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_ddw284.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5036356 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_dp2580.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_dp2580_flawed.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
(2) [ERROR]: AssertionError - After closing ABFile we get wrong content written to it! Here is how it was found: 1. New ABFile was created for writing. 2. Writeat was called with incorrect content (TerriblyWrongContent) 3. File was closed and reopened for reading. 4. Readat was called. Expected: SE, actual: SE1
Trying reference_monitor_dyt221.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_ec2590.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_fa961.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.4655894 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_fw678.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_gc1753.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.487555 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<class 'exception_hierarchy.FileClosedError'>' which is forbidden. 
---
Trying reference_monitor_gcr253.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_grp270.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.4843217 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_hd1004.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_hps257.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.488559 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<class 'exception_hierarchy.FileClosedError'>' which is forbidden. 
---
Trying reference_monitor_hs3500.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5039901 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_ht974.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.4717876 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_if497.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_jaa661.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5107158 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_jc5537.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5765841 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_jc8415.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5332685 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_jda388.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_jh4339.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
(2) [ERROR]: AssertionError - After closing ABFile we get wrong content written to it! Here is how it was found: 1. New ABFile was created for writing. 2. Writeat was called with incorrect content (TerriblyWrongContent) 3. File was closed and reopened for reading. 4. Readat was called. Expected: SE, actual: 
---
0.4898069 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_js7708.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.4878851 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_js7817.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.4920775 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_jw4321.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.4855385 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_jy1873.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5287163 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_jy2268.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5212712 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_ka1745.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5166062 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.IndexError'>' which is forbidden. 
---
Trying reference_monitor_kc1818.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5154027 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_kc2596.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_kc3289.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.4940409 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_kf1270.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_kg1965.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5140871 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_kjh398.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5367095 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<class 'exception_hierarchy.FileClosedError'>' which is forbidden. 
---
Trying reference_monitor_kn1049.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_kp1572.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.4962948 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<class 'exception_hierarchy.RepyArgumentError'>' which is forbidden. 
---
Trying reference_monitor_ks4703.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_ky1081.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.4849283 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<class 'exception_hierarchy.FileClosedError'>' which is forbidden. 
---
Trying reference_monitor_lac610.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_lcs456.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_ll3087.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.4744041 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<class 'exception_hierarchy.FileClosedError'>' which is forbidden. 
---
Trying reference_monitor_ln1026.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_lq437.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5081192 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_man514.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_met398.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_mg3933.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_mg4459.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5254984 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_mg5309.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5071412 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.IndexError'>' which is forbidden. 
---
Trying reference_monitor_mp3494.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.4708878 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<class 'exception_hierarchy.FileClosedError'>' which is forbidden. 
---
Trying reference_monitor_ms10625.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5099005 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.NameError'>' which is forbidden. 
---
Trying reference_monitor_msa530.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_na1489.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_naa355.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_ni444.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
TerriblyWrongContent
TerriblyWrongContent
SE
SErriblyWrongContent
---
0.4973061 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<type 'exceptions.AttributeError'>' which is forbidden. 
---
Trying reference_monitor_njt272.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_ntl247.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_ogi202.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_on371.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5200199 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<class 'exception_hierarchy.FileInUseError'>' which is forbidden. 
---
Trying reference_monitor_ork216.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_pb1826.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
---
0.5309638 Fatal Error: Function 'ABFile.close' tried to raise exception of type: '<class 'exception_hierarchy.FileClosedError'>' which is forbidden. 
---
Trying reference_monitor_pk1501.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
Trying reference_monitor_rg3365.r2py  with  dp2580_attempt2_invalidcontentwrittenclosed_expectedseonreading.r2py
